import { getSession } from 'next-auth/react';
import Head from 'next/head';
import NotablePlayers from '../src/components/NotablePlayers/NotablePlayers';
import Results from '../src/components/Results/Results';
import Tournament from '../src/components/Tournament/Tournament';
import supabase from '../src/lib/supabase/client';
import styles from '../styles/Home.module.css';

export default function Home({ userIsAdmin }: { userIsAdmin: boolean }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='google-signin-client_id'
          content='308312836672-mpph1meqftrivs6qavnechv75fttp3g5.apps.googleusercontent.com'
        ></meta>
        <script
          src='https://apis.google.com/js/platform.js'
          async
          defer
        ></script>

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Tournament tournament='Arlington 2022' allowEdits={userIsAdmin} />
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  const { data: administratorList } = await supabase
    .from('Administrators')
    .select('*');
  const userIsAdmin = administratorList?.some(
    admin => admin.email === session?.user?.email
  );

  return {
    props: { userIsAdmin },
  };
}
